Add retrying for baseline profile generation CI

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -106,11 +106,26 @@ jobs:
           arch: x86_64
           profile: pixel
           avd-name: emulator
-          script: >
-            ./gradlew macrobenchmark:connectedBenchmarkAndroidTest 
-            -Pandroid.testInstrumentationRunnerArguments.class=any.macrobenchmark.BaselineProfileGenerator 
-            -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" 
+          script: |
+            ATTEMPTS=5
+            for n in {1..$ATTEMPTS}; do
+            echo "Attempt $n"
+            ./gradlew macrobenchmark:connectedBenchmarkAndroidTest \
+            -Pandroid.testInstrumentationRunnerArguments.class=any.macrobenchmark.BaselineProfileGenerator \
+            -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" \
             -PdisableSplits
+            
+            exit_code=$?
+            if [ $exit_code -eq 0 ]; then
+            break
+            fi
+            
+            done
+        
+            if [ $exit_code -ne 0 ]; then
+            echo "Script execution failed after $ATTEMPTS attempts."
+            exit 1
+            fi
 
       - name: Copy baseline profile to app module
         if: ${{ inputs.build_release_apks }}
